### ISSUE TITLE
“object of type 'NoneType' has no len()” when starting with default config

### ISSUE THREAD

**Issue by progval** [kaniini/mammon#52]
```
$ ./mammond --config mammond.yml --nofork
Traceback (most recent call last):
  File "./mammond", line 26, in <module>
    ServerContext().run()
  File "/home/progval/irc/mammon/mammon/server.py", line 234, in run
    'server': self,
  File "/home/progval/.local/lib/python3.4/site-packages/ircreactor/events.py", line 75, in dispatch
    eo.dispatch(ev_msg)
  File "/home/progval/.local/lib/python3.4/site-packages/ircreactor/events.py", line 39, in dispatch
    [sub.callable(ev_msg) for sub in self.subscribers]
  File "/home/progval/.local/lib/python3.4/site-packages/ircreactor/events.py", line 39, in <listcomp>
    [sub.callable(ev_msg) for sub in self.subscribers]
  File "/home/progval/irc/mammon/mammon/ext/ircv3/register.py", line 47, in m_server_start
    if len(ctx.conf.register['enabled_callbacks']) == 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by DanielOaks** [comment]
Fixed, thanks for letting us know!

**Comment by progval** [comment]
Thanks for fixing it!
