### ISSUE TITLE
Crash if there is no registration callback configured

### ISSUE THREAD

**Issue by progval** [kaniini/mammon#58]
```
1 -> S: CAP LS 302
1 -> S: NICK registration_user
1 -> S: USER r e g :user
1 -> S: CAP END
S -> 1: :MyLittleServer CAP * LS * :account-tag echo-message metadata-notify cap-notify away-notify sasl=PLAIN server-time extended-join userhost-in-names
S -> 1: :MyLittleServer CAP * LS account-notify
S -> 1: :MyLittleServer NOTICE registration_user :*** Looking up your hostname...
S -> 1: :MyLittleServer NOTICE registration_user :*** Checking Ident
S -> 1: :MyLittleServer NOTICE registration_user :*** Found your hostname: localhost
S -> 1: :MyLittleServer NOTICE registration_user :*** No Ident response
S -> 1: :MyLittleServer 001 registration_user :Welcome to the MyLittleNetwork IRC Network, registration_user!~r@localhost
S -> 1: :MyLittleServer 002 registration_user :Your host is MyLittleServer, running version mammon-0
S -> 1: :MyLittleServer 003 registration_user :This server was started at Sun Dec 20 2015 at 12:33:59 CET
S -> 1: :MyLittleServer 004 registration_user MyLittleServer mammon-0 ioZw
S -> 1: :MyLittleServer 005 registration_user LINELEN= NICKLEN= MONITOR=20 CHANNELLEN= CHANTYPES=# NETWORK=MyLittleNetwork SAFELIST USERLEN= CASEMAPPING=rfc3454 METADATA TOPICLEN= :are supported by this server
S -> 1: :MyLittleServer 375 registration_user :- MyLittleServer Message of the Day -
S -> 1: :MyLittleServer 372 registration_user :- Hi
S -> 1: :MyLittleServer 376 registration_user :End of /MOTD command.
1 -> S: REG CREATE testuser temporarypassword
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 589, in _read_ready
    self._protocol.data_received(data)
  File "/home/progval/.local/lib/python3.4/site-packages/mammon-0.0.0-py3.4.egg/mammon/client.py", line 208, in data_received
    [self.message_received(m) for m in recvd]
  File "/home/progval/.local/lib/python3.4/site-packages/mammon-0.0.0-py3.4.egg/mammon/client.py", line 208, in <listcomp>
    [self.message_received(m) for m in recvd]
  File "/home/progval/.local/lib/python3.4/site-packages/mammon-0.0.0-py3.4.egg/mammon/client.py", line 228, in message_received
    self.drain_queue()
  File "/home/progval/.local/lib/python3.4/site-packages/mammon-0.0.0-py3.4.egg/mammon/client.py", line 233, in drain_queue
    self.eventmgr.dispatch(*m.to_event())
  File "/home/progval/.local/lib/python3.4/site-packages/mammon-0.0.0-py3.4.egg/mammon/events.py", line 77, in dispatch
    eo.dispatch(ev_msg)
  File "/home/progval/.local/lib/python3.4/site-packages/ircreactor/events.py", line 39, in dispatch
    [sub.callable(ev_msg) for sub in self.subscribers]
  File "/home/progval/.local/lib/python3.4/site-packages/ircreactor/events.py", line 39, in <listcomp>
    [sub.callable(ev_msg) for sub in self.subscribers]
  File "/home/progval/.local/lib/python3.4/site-packages/mammon-0.0.0-py3.4.egg/mammon/events.py", line 99, in child_fn
    return func(cli, ev_msg)
  File "/home/progval/.local/lib/python3.4/site-packages/mammon-0.0.0-py3.4.egg/mammon/ext/ircv3/register.py", line 103, in m_REG
    if enabled_cb_types[0] == 'none' and len(enabled_cb_types) > 1:
IndexError: list index out of range
```

**Comment by progval** [comment]
Same for `verify_timeout`:

```
Traceback (most recent call last):
  File "/home/progval/.local/bin/mammond", line 4, in <module>
    __import__('pkg_resources').run_script('mammon==0.0.0', 'mammond')
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/home/progval/.local/lib/python3.4/site-packages/mammon-0.0.0-py3.4.egg/EGG-INFO/scripts/mammond", line 26, in <module>
  File "/home/progval/.local/lib/python3.4/site-packages/mammon-0.0.0-py3.4.egg/mammon/server.py", line 241, in run
  File "/home/progval/.local/lib/python3.4/site-packages/ircreactor/events.py", line 75, in dispatch
    eo.dispatch(ev_msg)
  File "/home/progval/.local/lib/python3.4/site-packages/ircreactor/events.py", line 39, in dispatch
    [sub.callable(ev_msg) for sub in self.subscribers]
  File "/home/progval/.local/lib/python3.4/site-packages/ircreactor/events.py", line 39, in <listcomp>
    [sub.callable(ev_msg) for sub in self.subscribers]
  File "/home/progval/.local/lib/python3.4/site-packages/mammon-0.0.0-py3.4.egg/mammon/ext/ircv3/register.py", line 70, in m_server_start
KeyError: 'verify_timeout'
```
